version: "3.1"
services:
    xml_pg:
        image: haifengat/xml_tick_pg
        container_name: xml_pg
        restart: always
        environment:
            - TZ=Asia/Shanghai
            - xml_zip_path=/xml
            - pg_conn=postgres://postgres:123456@pg_tick:5432/postgres
        volumes:
            - /mnt/future_xml:/xml
        depends_on:
            - pg_tick

    pg_tick:
        image: postgres:12
        container_name: pg_tick
        restart: always
        environment:
            - TZ=Asia/Shanghai
            - POSTGRES_PASSWORD=123456
        ports:
            - "35432:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data
